### ISSUE TITLE
src/test/groovy disappearing from the classpath when updating maven project

### ISSUE THREAD

**Issue by jjurkiewicz** [groovy/groovy-eclipse#192] opened 2016-08-10 02:14 UTC
We have a java maven project with spock tests. The tests are located in src/test/groovy. We used to be able to run these tests in Eclipse with org.codehaus.groovy.m2eclipse_2.9.2.xx-201604081629-e45 installed. When we updated this plugin to org.codehaus.groovy.m2eclipse_2.9.2.xx-201607251752-e45 no longer we can run the tests. Today I've noticed that the problem is even when running Update Maven Project action (Alt+F5). Whenever the action is ran the source folder src/test/groovy disappears from the classpath.

**Comment by reckart** [comment] 2016-08-12 05:09
Looks like a duplicate of #191. Possible solutions are being discussed there. Best have a look.

**Comment by eric-milles** [comment] 2017-07-27 15:15
@jjurkiewicz I believe I fixed this yesterday. The class path entries needed to be touched during the update. I saw the same add and remove toggling for both arc/main/groovy and arc/test/groovy during testing. 

Can you retest with the latest snapshot?

**Closed** 2017-07-28 13:58 UTC
