### ISSUE TITLE
java.lang.NoClassDefFoundError when using JDK-10

### ISSUE THREAD

**Issue by boris-petrov** [groovy/groovy-eclipse#589] opened 2018-05-22 13:26 UTC
Sorry if this has been asked already, I couldn't find anything. I'm getting a:

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class org.codehaus.groovy.jsr223.ScriptStaticExtensions due to missing dependency javax/script/ScriptEngineManager
        at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1169)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1147)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:604)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:581)
        at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.processToPhase(GroovyCompilationUnitDeclaration.java:215)
        at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.generateCode(GroovyCompilationUnitDeclaration.java:320)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:908)
        at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:141)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: Unable to load class org.codehaus.groovy.jsr223.ScriptStaticExtensions due to missing dependency javax/script/ScriptEngineManager
        at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:429)
        at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:358)
        at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:480)
...
```

When pointing Eclipse to my JDK-10 installation and compiling my project with Groovy code for Java 10. Am I missing something?

**Comment by eric-milles** [comment] 2018-05-22 20:48
Duplicate of #582

**Closed by eric-milles** 2018-05-22 20:48 UTC
