### ISSUE TITLE
No way to enable static type checking on the compiler in maven

### ISSUE THREAD

**Issue by apottere** [groovy/groovy-eclipse#158] opened 2015-12-08 17:20 UTC
Per this SA: http://stackoverflow.com/questions/16074219/static-compile-groovy-by-default-using-maven

I would like a way to tell the compiler to always compile static in a maven project.

It looks like this was tracked on the old codehaus issue tracking as GRECLIPSE-1615 - if this is already tracked somewhere else please let me know.

**Comment by eric-milles** [comment] 2017-01-28 17:29
Duplicate of issue #127.

**Closed by eric-milles** 2017-01-28 17:29 UTC
