### ISSUE TITLE
Use Parrot without configuration with Groovy 4+

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1362] opened 2022-05-19 01:18 UTC
As of Groovy 4.0, Parrot is the only parser, but GRECLIPSE will still try to use the old parser unless the magic property is set. If the workspace is launching in 4.0 mode, Parrot should be activated.

**Comment by Spitfire1900** [comment] 2022-05-26 17:46
Should be closed as duplicate of #1011

**Closed as completed** 2022-06-15 16:49 UTC
