### ISSUE TITLE
Batch compiler does not compile Groovy 3 Java-style lambdas

### ISSUE THREAD

**Issue by kriegaex** [groovy/groovy-eclipse#1137] opened 2020-07-05 12:49 UTC
I have used Groovy Eclipse Batch Compiler from Maven for years in order to compile my Spock tests. I am not a Groovy expert, though. I was just curious and wanted to add some lambdas to my Spock tests because according to the Groovy 3 manual the syntax is supported now. Probably I am doing something phenomenally stupid, but neither from Maven nor from IntelliJ IDEA I can compile my class. Do I need to use any specific compiler switch?

**Comment by eric-milles** [comment] 2020-07-05 15:00
If you set the system property `groovy.antlr4` to true, the new parser will be used if you have Groovy 3 dependency defined for the batch compiler.  Sorry about this, it was meant to be off for IDE but on for batch compiler.

Duplicate of #1107

**Closed by eric-milles** 2020-07-05 15:00 UTC
