### ISSUE TITLE
Add support for Java 9 to Groovy-Eclipse Maven plugin (aka batch compiler)

### ISSUE THREAD

**Issue by johnpoth** [groovy/groovy-eclipse#265] opened 2017-02-15 16:19 UTC
I'm using the following configuration with java 9 build 156
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
          <source>8</source>
          <target>8</target>
          <fork>true</fork>-
          <compilerArgs>
            <arg>-J--add-modules</arg>  // add java.xml module!
            <arg>-Jjava.xml</arg>
          </compilerArgs>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>2.9.2-01</version>
            <exclusions>
              <exclusion>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy-eclipse-batch</artifactId>
              </exclusion>
            </exclusions>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>2.4.3-01</version>
          </dependency>
        </dependencies>
      </plugin>
```
But I still get the error

```
TransformerException cannot be resolved to a type
```

Where javax/xml/transform/TransformerException is a class present in the java 9 module called java.xml. The above works with the maven compiler plugin.

Am I doing something wrong or is java 9 not supported yet?

Thanks!

**Comment by eric-milles** [comment] 2017-02-16 15:21
I'm not sure where Java 9 support begins and ends exactly.  You may need to bootstrap modules to the classpath for this to work with the 2.4.3 compiler.  In development we have the 2.4.8 compiler in place.  Not sure if it has better support.  We'd need to get a release of it so you could reference it in your POM.

**Comment by eric-milles** [comment] 2017-10-07 23:12
As soon as Eclipse Oxygen 4.7.1a is released, I will publish a Java 9 compatible batch compiler.

**Comment by ispringer** [comment] 2017-10-12 03:18
Eclipse Oxygen 4.7.1a has been released.

https://www.eclipse.org/eclipse/news/4.7.1a/

**Comment by eric-milles** [comment] 2017-10-13 16:12
Batch compiler 2.4.12-05 is available from bintray.  There are a couple hitches that require a few changes to your POM.  If you follow [these instructions](https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin) to get to a stable Java 8 build, you can make the following changes to get Java 9 to go.  _Be sure to adjust any existing Maven run configurations to use a Java 9 execution environment._

```xml
  <properties>
    <maven.compiler.fork>false</maven.compiler.fork>
    <maven.compiler.source>9</maven.compiler.source>
    <maven.compiler.target>9</maven.compiler.target>
  </properties>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
          <compilerArgument>${maven.compiler.source}</compilerArgument>
        </configuration>
        ...
```

Until [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=519600) is resolved, the compliance level must be passed in as an argument, which is what `<compilerArgument>${maven.compiler.source}</compilerArgument>` accomplishes.

If you want to run with a forked compiler, I believe the `java.compiler` module must be added to the forked VM.  I haven't worked out exactly what to set in the POM to make this work.  I will probably look to fix this in the compiler adapter at some point.

You should be able to add modules to the compilation modulepath with `<compilerArgument>--add-modules=ALL-SYSTEM</compilerArgument>` or whatever.  Supported compiler arguments are listed [here](https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm).  Although it does not appear to have been updated for the Java 9 changes yet.

**Comment by ispringer** [comment] 2017-10-14 02:33
Thank you!

It seems like there may be a regression in this new version of the compiler. I get a compiler error that I didn't previously get, which seems invalid.

I have a Groovy class that looks like this:

```
package com.foo

class TestUserAgents {
    static final String[] DESKTOP_AGENTS = ["blah"]
}
```

which I then static import into another Groovy class as follows:

```
import static com.foo.TestUserAgents.DESKTOP_AGENTS
```

And I am getting the following compile error:

```
	import static com.foo.TestUserAgents.DESKTOP_AGENTS
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The field TestUserAgents.com.foo.TestUserAgents.DESKTOP_AGENTS is not visible
```

Adding the "public" modifier to 'static final String[] DESKTOP_AGENTS = ["blah"]' fixes the error, but it doesn't seem like I should have to do that...

Any idea what might be going on?

Note, I'm using JDK8, not JDK9.

**Comment by eric-milles** [comment] 2017-10-15 03:05
The issue you mention was raised as #336.  Without the public modifier, Groovy creates a private field of the given name and a public accessor method.  The import checking occurs against the field and not the accessor.  If I were to disable the checking that is at play here, some other added checks like null annotations would also go away.  That is why I recommend the `public` modifier as you mentioned and marked the issue as Won't Fix.

**Comment by Zoden** [comment] 2017-10-22 20:03
Hi!

I'm trying to use `2.4.12-05` now, but I've got such an error:

`java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findDirectMemberType(Scope.java:1250)`

It seems to be fixed in this issues:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=520658
https://bugs.eclipse.org/bugs/show_bug.cgi?id=486013

4.8M2 is out some days ago, according to this [plan](https://projects.eclipse.org/projects/eclipse/releases/4.8.0/plan)

The question is - is there any place to get snapshot build of batch compiler with all latest changes?
 
I've tried this https://build.spring.io/browse/GRECLIPSE-GE47 but without any luck. Maybe I'm looking in a wrong place?

Thank you!

**Comment by eric-milles** [comment] 2017-10-22 21:40
Eclipse 4.8M2 does not contain the Java 9 support.  I think M3 will have it.  If you don't need Java 9 support, 2.4.12-04 should work better.

If you wish to create an updated compiler artifact, you can clone this repository and get a zip of [JDT Core](https://github.com/eclipse/eclipse.jdt.core) at any commit you like.  When you diff the org.eclipse.jdt.core project between the two, you would move in any changes that are not marked as `// GROOVY ...` in this repo.

Then the steps to create a new batch compiler are [here](https://github.com/groovy/groovy-eclipse/wiki/Building-Maven-Batch-Compiler).  The batch compiler is not built as part of the CI builds.

**Closed** 2017-10-31 22:55 UTC
Labels: Enhancement
