### ISSUE TITLE
"Organize imports" on packages has different output than on files.

### ISSUE THREAD

**Issue by ViToni** [groovy/groovy-eclipse#897] opened 2019-05-24 11:44 UTC
On a large project I wanted to clean up / order / organize the imports we have in our Groovy files.

When doing this on a package some imports get deleted which would appear again  / would not be deleted when individually doing the "Organize import" on a file. As some of the imports areambigous this needs manual intervention.

Very problematic is using static import for constant only classes because if the class dissappers it is very difficult to find the original one.

Issue occurred with:
3.4.0.v201905231728-e1812	org.codehaus.groovy.eclipse.feature.feature.group

**Comment by eric-milles** [comment] 2019-05-24 16:41
Duplicate of #238

**Closed** 2019-05-24 16:42 UTC
Labels: duplicate

**Comment by ViToni** [comment] 2019-05-25 20:28
I'm not sure if this is really about formatting. Maybe the title of #238 is misleading me...
On Windows I can use `Ctrl+Shift+o` in the editor or on the package itself to organize imports. This issue is about that doing "orgaize imports" on the package is distructive.

**Comment by eric-milles** [comment] 2019-09-18 14:48
Any of these actions that can be applied to a package, source folder or other container of Java and Groovy sources suffers the same problem.  The Java action is executed.  A suitable action needs to be installed that can drive the Java action for java sources and the Groovy action for groovy sources.
