### ISSUE TITLE
Parrot parser not used with maven-compiler-plugin when configured as documented

### ISSUE THREAD

**Issue by cstamas** [groovy/groovy-eclipse#1107] opened 2020-04-30 13:11 UTC
So if a the doco is followed to set up your Maven, the Parrot parser seems not used, see https://github.com/groovy/groovy-eclipse/issues/1082

I believe this is worth documenting, as it causes HUGE discrepancy between what user reads on Groovy3 and whar Maven "eats" when configured as documented. Moreover, IDEs like Idea, when setup like this, does NOT behave as this (follows Groovy doco, does not need this system property to enable parrot parser).

Hence, this should be documented, on a very visible place. Plus: doco should get into detail how to setup maven compiler plugin to get "real" Groovy 3 as well.

**Comment by eric-milles** [comment] 2020-04-30 14:35
I'll definitely need some clarification on your use case.  Parrot Parser is disabled by default in Eclipse IDE and this has been stated in the release notes for every release that includes the new parser.  The Maven batch compiler was not released until Groovy 3 was released and the compiler artifact was designed and tested to use the Parrot Parser.  Since live editing is not involved, there was no reason to disable the new parser.  If you are not using Eclipse IDE or Maven builds, what is your situation where the new parser is expected but is not appearing to be used?

**Comment by cstamas** [comment] 2020-04-30 14:49
Am using it as documented on this site, but try-with-resource does NOT compile (on CLI, using `mvn clean install`), just like in referenced issue. Moreover, it DOES compile if I append `-Dgroovy.antlr4=true` to my command line. Hence, this shows that when used with Maven only (so no IDE involved), it still needs this system property.

**Comment by cstamas** [comment] 2020-04-30 15:04
So here is an example project
- hopefully is configured right
- but does not compile

I get error
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project maven-eclipse-compiler-1107: Compilation failure: Compilation failure: 
[ERROR] /home/cstamas/tmp/maven-with-groovy/maven-eclipse-compiler-1107/src/main/java/org/cstamas/test/App.groovy:[10,5] 
[ERROR] 1. ERROR in /home/cstamas/tmp/maven-with-groovy/maven-eclipse-compiler-1107/src/main/java/org/cstamas/test/App.groovy (at line 10)
[ERROR] 	try (FileInputStream fis = new FileInputStream('test')) {
[ERROR] 	    ^
[ERROR] Groovy:expecting '{', found '('
[ERROR] Found 1 error and 0 warnings.
[ERROR] -> [Help 1]
```

but, when I do `mvn install -Dgroovy.antlr4=true`, then it compiles just fine.

Am I doing something wrong?

**Comment by cstamas** [comment] 2020-04-30 15:11
And setting it for "real" (the thing I mention on OP) is quite cumbersome, as **setting a system property from POM alone is not possible**, unless you get an extra plugin, and use that.

Why not just plain compiler argument instead (that maven-compiler-plugin already supports)? Also, why this (IMO wrong) default when used from Maven?

**Comment by eric-milles** [comment] 2020-04-30 15:47
The long term goal is to [support recovery for the new parser](https://github.com/groovy/groovy-eclipse/issues/1011) and at that point there will be no reason to disable it by default.

**Comment by kriegaex** [comment] 2020-07-05 16:06
I am commenting here instead of in my duplicate #1137, in order to return something to the helpful community and hopefully for the benefit of others stumbling upon this problem too. Here is how I configure my IDE IntelliJ IDEA to use `-Dgroovy.antlr4=true` for both Maven and IDEA builds:

![image](https://user-images.githubusercontent.com/1537384/86536734-1b825980-bf14-11ea-91b3-563fe391bb8d.png)

![image](https://user-images.githubusercontent.com/1537384/86536747-263cee80-bf14-11ea-93d4-fefcdf0a3a72.png)

**Comment by brandones** [comment] 2020-11-20 22:34
@cstamas Could you explain how you've used the `properties-maven-plugin` to set `groovy.antlr4`? Seeing a snippet of POM would be incredibly helpful.

**Comment by cstamas** [comment] 2020-11-20 22:52
Howdy, of course:
```
        <!-- Set system properties -->
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>properties-maven-plugin</artifactId>
          <version>1.0.0</version>
          <executions>
            <execution>
              <goals>
                <goal>set-system-properties</goal>
              </goals>
              <configuration>
                <properties>
                  <!-- Make groovy-eclipse-compiler use Groovy 3 compiler -->
                  <property>
                    <name>groovy.antlr4</name>
                    <value>true</value>
                  </property>
                </properties>
              </configuration>
            </execution>
          </executions>
        </plugin>
```

**Comment by brandones** [comment] 2020-11-20 23:01
Perfect, thanks so much!

**Comment by eric-milles** [comment] 2021-06-03 18:00
A couple notes that might be useful:

1. If using maven to compile, the forked mode of the compiler does indeed enable the Parrot Parser for Groovy 3+.  This can be done by adding `<maven.compiler.fork>true</maven.compiler.fork>` to your `properties` element or `<fork>true</fork>` to your `maven-compiler-plugin`'s `configuration` element.

2. As noted earlier, you can also enable the Parrot Parser by adding a compiler config script.  This can be done by adding `<compilerArguments><configScript>config.groovy</configScript></compilerArguments>` to your `maven-compiler-plugin`'s `configuration` element.  `config.groovy` should contain:
    ```groovy
    configuration.pluginFactory = org.codehaus.groovy.control.ParserPluginFactory.antlr4()
    ```

3. IntelliJ does not use the `Main-Class` as specified by the `groovy-eclipse-batch` jar.  This means [it bypasses](https://github.com/JetBrains/intellij-community/blob/7262e78eb0ffea99c375458a9291500ecf2ca4a3/plugins/groovy/jps-plugin/src/org/jetbrains/jps/incremental/groovy/GreclipseMain.java) the [extra config](https://github.com/groovy/groovy-eclipse/blob/master/jdt-patch/e414/org.eclipse.jdt.core/batch/org/eclipse/jdt/internal/compiler/batch/Main.java#L1498) that was put in place to have the batch compiler use Parrot Parser by default.

**Comment by kriegaex** [comment] 2021-06-06 02:02
Thanks for the Maven Compiler fork setting. It works nicely for me. So now in IntelliJ IDEA I no longer need to set the property in the Maven runner VM settings as described in https://github.com/groovy/groovy-eclipse/issues/1107#issuecomment-653906682. For the Groovy-Eclipse compiler, I still need the property, though. I do not want to use a compiler config script, because that would be even more complicated and just be another extra IDE setting I need, i.e. nothing would improve that way with regard to my goal "simply import the Maven project and it works".

@eric-milles, did you open an issue at JetBrains for this issue in order to get it fixed? If not, I can create one on your behalf. I want to push this to get fixed one way or another.

**Comment by mattventura** [comment] 2023-08-17 19:00
I also ran into this problem and only found this issue after a lot of searching. I think it would make sense to just update the wiki's example POM or at least add a comment there. It's an easy fix once someone knows that the problem is that they need to enable the antlr4 parser, but as it stands you have to dig through the issues or old release notes to find it.

**Comment by kriegaex** [comment] 2023-08-17 21:42
Actually, I am not sure why the idea from the last paragraph of my previous comment https://github.com/groovy/groovy-eclipse/issues/1107#issuecomment-855323869 was not implemented yet. It would be simple and fix the problem in several use cases.

**Comment by eric-milles** [comment] 2023-08-23 14:58
@cstamas @mattventura I updated the docs to make specific mention of the fork setting:  https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin#how-to-use-the-compiler-plugin---setting-up-the-pom

@kriegaex The design of this was to respect the system properties of a shared jvm.  When forking the compiler process, it is safe enough to set the system property that enables antlr4 parser.  It was unanticipated that IntelliJ uses a different entry point.  The long-term goal is still to improve parser error recovery and then enable it by default -- as `groovyc` does.

**Closed by eric-milles** 2023-08-23 14:58 UTC
Labels: maven
